helm: Fix preflight check resource quota conflict
[ upstream pr cilium/cilium#14295 ]

This commit fixes the preflight check on GKE which currently conflicts
with the resource quotas that may be present from an already installed
Cilium version:

```
Error: rendered manifests contain a resource that already exists. Unable
to continue with install: existing resource conflict: kind:
ResourceQuota, namespace: cilium, name: cilium-resource-quota
```

Fixes: 14ff743 ("gke: add resource quotas for Cilium namespace")

Signed-off-by: Sebastian Wicki <sebastian@isovalent.com>